apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8s-training-server-storage
  labels:
    app.kubernetes.io/name: k8s-training-server
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10M
