apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-training-server.fullname" . }}
  labels:
    {{- include "k8s-training-server.labels" . | nindent 4 }}
data:
  RESPONSE: Hello Kubernetes via helm!
